# words_data.py
# Mixed difficulty word bank: daily-use simple words + tougher/advanced words
# Each entry: word, meaning (simple English), hindi (proper Devanagari meaning), example sentence

WORDS = [
    {"word": 'Abundant', "meaning": 'Existing in large quantity; plentiful', "hindi": 'बहुत ज़्यादा / प्रचुर मात्रा में', "example": 'The region has abundant natural resources.'},
    {"word": 'Ambiguous', "meaning": 'Open to more than one interpretation; unclear', "hindi": 'अस्पष्ट, जिसका मतलब स्पष्ट न हो', "example": 'His answer was ambiguous, so I asked again.'},
    {"word": 'Blunt', "meaning": 'Very direct in speech; not sharp (for objects)', "hindi": 'सीधा-साफ बोलने वाला / कुंद', "example": 'She gave a blunt reply without any hesitation.'},
    {"word": 'Candid', "meaning": 'Truthful and straightforward; frank', "hindi": 'सच्चा और सीधा', "example": 'I want your candid opinion on this plan.'},
    {"word": 'Deliberate', "meaning": 'Done on purpose; intentional', "hindi": 'जान-बूझकर किया गया', "example": 'It was a deliberate attempt to mislead us.'},
    {"word": 'Diligent', "meaning": 'Showing care and effort in work', "hindi": 'मेहनती, लगन से काम करने वाला', "example": 'She is a diligent student who never skips homework.'},
    {"word": 'Eager', "meaning": 'Very keen or enthusiastic to do something', "hindi": 'उत्सुक, कुछ करने के लिए बेताब', "example": 'He was eager to start his new job.'},
    {"word": 'Feasible', "meaning": 'Possible to do easily or practically', "hindi": 'व्यावहारिक, जो हो सकता है', "example": 'Is it feasible to finish this by tomorrow?'},
    {"word": 'Genuine', "meaning": 'Real and authentic; not fake', "hindi": 'असली, सच्चा', "example": 'His apology seemed genuine.'},
    {"word": 'Hesitant', "meaning": 'Slow to act due to uncertainty', "hindi": 'संशय में, झिझकने वाला', "example": 'She was hesitant to share her idea in the meeting.'},
    {"word": 'Immense', "meaning": 'Extremely large in size or degree', "hindi": 'विशाल, बहुत बड़ा', "example": 'The project needed an immense amount of effort.'},
    {"word": 'Jovial', "meaning": 'Cheerful and friendly', "hindi": 'खुश-मिज़ाज़, हंसमुख', "example": 'The host was jovial and made everyone comfortable.'},
    {"word": 'Keen', "meaning": 'Having a strong interest or enthusiasm', "hindi": 'उत्सुक, गहरी रुचि रखने वाला', "example": 'He is keen on learning new languages.'},
    {"word": 'Legitimate', "meaning": 'Conforming to the law or accepted standards', "hindi": 'वैध, कानूनी', "example": 'He has a legitimate reason for being late.'},
    {"word": 'Meticulous', "meaning": 'Showing great attention to detail', "hindi": 'बहुत सूक्ष्म ध्यान देने वाला', "example": 'She is meticulous about checking her work twice.'},
    {"word": 'Notable', "meaning": 'Worthy of attention; remarkable', "hindi": 'उल्लेखनीय, ध्यान देने लायक', "example": 'There was a notable improvement in his scores.'},
    {"word": 'Obsolete', "meaning": 'No longer in use; outdated', "hindi": 'पुराना, अब इस्तेमाल न होने वाला', "example": 'This software is now obsolete.'},
    {"word": 'Plausible', "meaning": 'Seeming reasonable or believable', "hindi": 'विश्वसनीय, संभव लगने वाला', "example": "That's a plausible explanation for the delay."},
    {"word": 'Quaint', "meaning": 'Attractively unusual or old-fashioned', "hindi": 'पुराने ढंग से सुंदर', "example": 'We stayed in a quaint little village.'},
    {"word": 'Reluctant', "meaning": 'Unwilling to do something', "hindi": 'अनिच्छुक, करने में न चाहना', "example": 'He was reluctant to accept the offer.'},
    {"word": 'Skeptical', "meaning": 'Not easily convinced; having doubts', "hindi": 'संदेही, आसानी से विश्वास न करने वाला', "example": "I'm skeptical about his promises."},
    {"word": 'Tedious', "meaning": 'Too long, slow, or dull; tiresome', "hindi": 'उबाऊ, थकाऊ', "example": 'Filling out these forms is tedious.'},
    {"word": 'Unanimous', "meaning": 'Fully in agreement', "hindi": 'सर्वसम्मत, सबकी सहमति वाला', "example": 'The decision was unanimous.'},
    {"word": 'Vague', "meaning": 'Not clear or precise', "hindi": 'अस्पष्ट', "example": 'His directions were too vague to follow.'},
    {"word": 'Wary', "meaning": 'Cautious about possible danger', "hindi": 'सावधान, खतरे से सतर्क', "example": 'Be wary of strangers asking for money.'},
    {"word": 'Zealous', "meaning": 'Showing great energy in pursuit of something', "hindi": 'जोश से भरा हुआ', "example": 'He is a zealous supporter of the cause.'},
    {"word": 'Adequate', "meaning": 'Enough or satisfactory for a purpose', "hindi": 'पर्याप्त, काफी', "example": 'We have adequate supplies for the trip.'},
    {"word": 'Brittle', "meaning": 'Hard but easily broken', "hindi": 'भुरभुरा, आसानी से टूटने वाला', "example": 'The old paper had become brittle.'},
    {"word": 'Concise', "meaning": 'Giving information clearly in few words', "hindi": 'संक्षिप्त, थोड़े शब्दों में', "example": 'Please write a concise summary.'},
    {"word": 'Diverse', "meaning": 'Showing a lot of variety', "hindi": 'विविध, अलग-अलग तरह का', "example": 'The company has a diverse team.'},
    {"word": 'Elaborate', "meaning": 'Detailed and complicated', "hindi": 'विस्तृत, जटिल', "example": 'They made elaborate plans for the wedding.'},
    {"word": 'Flexible', "meaning": 'Able to change or adapt easily', "hindi": 'लचीला, बदलाव के लिए तैयार', "example": 'My work hours are quite flexible.'},
    {"word": 'Gratitude', "meaning": 'The feeling of being thankful', "hindi": 'कृतज्ञता, धन्यवाद का भाव', "example": 'She expressed her gratitude for the help.'},
    {"word": 'Humble', "meaning": 'Not proud; modest', "hindi": 'विनम्र', "example": 'Despite his success, he remains humble.'},
    {"word": 'Inevitable', "meaning": 'Certain to happen; unavoidable', "hindi": 'अनिवार्य, जो होना ही है', "example": 'Change is inevitable in life.'},
    {"word": 'Justify', "meaning": 'To show or prove to be right', "hindi": 'उचित ठहराना', "example": 'Can you justify your decision?'},
    {"word": 'Lucrative', "meaning": 'Producing a lot of profit', "hindi": 'लाभदायक, फायदे वाला', "example": 'He found a lucrative business opportunity.'},
    {"word": 'Mundane', "meaning": 'Lacking excitement; ordinary', "hindi": 'साधारण, रोज़ का', "example": 'He was tired of his mundane routine.'},
    {"word": 'Neglect', "meaning": 'To fail to take care of something', "hindi": 'उपेक्षा करना', "example": "Don't neglect your health for work."},
    {"word": 'Optimistic', "meaning": 'Hopeful about the future', "hindi": 'आशावादी', "example": 'She is optimistic about passing the exam.'},
    {"word": 'Persuade', "meaning": 'To convince someone to do something', "hindi": 'मनाना, समझाना', "example": 'I tried to persuade him to join us.'},
    {"word": 'Quench', "meaning": 'To satisfy thirst or extinguish something', "hindi": 'बुझाना (प्यास या आग)', "example": 'This drink will quench your thirst.'},
    {"word": 'Resilient', "meaning": 'Able to recover quickly from difficulties', "hindi": 'मुश्किलों से जल्दी उभरने वाला', "example": 'Children are often more resilient than adults.'},
    {"word": 'Substantial', "meaning": 'Of considerable importance or size', "hindi": 'काफी बड़ा / महत्वपूर्ण', "example": 'There was a substantial increase in sales.'},
    {"word": 'Thrive', "meaning": 'To grow or develop successfully', "hindi": 'फलना-फूलना, उन्नति करना', "example": 'Small businesses thrive in this market.'},
    {"word": 'Underlying', "meaning": 'The basic or true cause of something', "hindi": 'मूल कारण, जो सामने नहीं दिखता', "example": 'We need to find the underlying issue.'},
    {"word": 'Versatile', "meaning": 'Able to adapt to many functions', "hindi": 'बहुमुखी, कई कामों में माहिर', "example": 'She is a versatile actress.'},
    {"word": 'Withhold', "meaning": 'To refuse to give something', "hindi": 'रोकना, न देना', "example": 'The company withheld his salary by mistake.'},
    {"word": 'Yearn', "meaning": 'To have an intense desire for something', "hindi": 'तरसना, बहुत चाहना', "example": 'He yearns to visit his hometown.'},
    {"word": 'Zestful', "meaning": 'Full of energy and enthusiasm', "hindi": 'जोश और उत्साह से भरा', "example": 'She gave a zestful performance on stage.'},
    {"word": 'Accomplish', "meaning": 'To achieve or complete successfully', "hindi": 'पूरा करना, सफल होना', "example": 'We accomplished our goal ahead of time.'},
    {"word": 'Benevolent', "meaning": 'Kind and generous', "hindi": 'दयालु, परोपकारी', "example": 'The benevolent donor funded the school.'},
    {"word": 'Coherent', "meaning": 'Logical and consistent; easy to understand', "hindi": 'तर्कसंगत, समझ में आने वाला', "example": 'Write a coherent essay with clear points.'},
    {"word": 'Deceive', "meaning": 'To make someone believe something untrue', "hindi": 'धोखा देना', "example": 'He tried to deceive his customers.'},
    {"word": 'Empathy', "meaning": "The ability to understand others' feelings", "hindi": 'संवेदना, दूसरों की भावना समझना', "example": 'A good leader shows empathy toward the team.'},
    {"word": 'Frugal', "meaning": 'Careful with money; not wasteful', "hindi": 'किफायती, कम खर्च करने वाला', "example": 'She leads a frugal lifestyle to save money.'},
    {"word": 'Grim', "meaning": 'Very serious or gloomy', "hindi": 'गंभीर, उदास करने वाला', "example": 'The news brought a grim expression to his face.'},
    {"word": 'Hinder', "meaning": "To create difficulty for someone's progress", "hindi": 'रुकावट डालना', "example": 'Bad weather hindered our travel plans.'},
    {"word": 'Impartial', "meaning": 'Not favoring one side; fair', "hindi": 'निष्पक्ष', "example": 'The judge remained impartial throughout the trial.'},
    {"word": 'Jeopardy', "meaning": 'Danger of loss or harm', "hindi": 'खतरे में', "example": 'His careless driving put everyone in jeopardy.'},
    {"word": 'Kindle', "meaning": 'To light a fire, or to inspire a feeling', "hindi": 'जलाना, जगाना', "example": 'The story kindled hope in the readers.'},
    {"word": 'Lenient', "meaning": 'More merciful or tolerant than expected', "hindi": 'नरम, कम सज़ा देने वाला', "example": 'The teacher was lenient with late submissions.'},
    {"word": 'Meager', "meaning": 'Lacking in quantity; small', "hindi": 'कम, थोड़ा', "example": 'He survived on a meager income.'},
    {"word": 'Nurture', "meaning": 'To care for and help grow', "hindi": 'पोषण करना, देखभाल करना', "example": "Parents nurture their children's talents."},
    {"word": 'Obstinate', "meaning": "Stubborn; refusing to change one's mind", "hindi": 'जिद्दी', "example": 'He is too obstinate to accept advice.'},
    {"word": 'Prudent', "meaning": 'Acting with care and thought for the future', "hindi": 'विवेकपूर्ण, समझदारी से', "example": "It's prudent to save money every month."},
    {"word": 'Quirky', "meaning": 'Unusual in an interesting or appealing way', "hindi": 'विचित्र पर प्यारा', "example": 'She has a quirky sense of humor.'},
    {"word": 'Rigid', "meaning": 'Not able to bend; strict', "hindi": 'कठोर, सख्त', "example": 'The rules here are quite rigid.'},
    {"word": 'Scrutinize', "meaning": 'To examine closely and carefully', "hindi": 'बारीकी से जांचना', "example": 'The auditor scrutinized every transaction.'},
    {"word": 'Tentative', "meaning": 'Not certain or fixed; provisional', "hindi": 'अस्थायी, पक्का नहीं', "example": 'We have a tentative plan for the weekend.'},
    {"word": 'Utmost', "meaning": 'The greatest or highest degree', "hindi": 'सबसे ज़्यादा', "example": 'Please handle this matter with utmost care.'},
    {"word": 'Vivid', "meaning": 'Producing powerful, clear images in the mind', "hindi": 'स्पष्ट और जीवंत', "example": 'She gave a vivid description of the accident.'},
    {"word": 'Wither', "meaning": 'To become dry and shriveled', "hindi": 'मुरझाना, सूखना', "example": 'The flowers began to wither in the heat.'},
    {"word": 'Yield', "meaning": 'To produce or give way to something', "hindi": 'पैदावार देना / झुकना', "example": 'This land yields a good harvest every year.'},
    {"word": 'Zenith', "meaning": 'The highest point or peak', "hindi": 'शिखर, उच्चतम बिंदु', "example": 'He reached the zenith of his career.'},
    {"word": 'Anticipate', "meaning": 'To expect or predict something', "hindi": 'पहले से अनुमान लगाना', "example": 'We anticipate heavy traffic this evening.'},
    {"word": 'Bewildered', "meaning": 'Confused and puzzled', "hindi": 'हैरान-परेशान', "example": 'She looked bewildered by the sudden question.'},
    {"word": 'Comply', "meaning": 'To act according to a rule or request', "hindi": 'पालन करना', "example": 'All employees must comply with the new policy.'},
    {"word": 'Dismal', "meaning": 'Depressing or dreary', "hindi": 'उदास, निराशा भरा', "example": 'The weather was dismal all week.'},
    {"word": 'Endeavor', "meaning": 'A serious attempt or effort', "hindi": 'प्रयास, कोशिश', "example": 'This is a noble endeavor worth supporting.'},
    {"word": 'Fickle', "meaning": 'Changing frequently, especially in loyalty', "hindi": 'चंचल, मन बदलने वाला', "example": 'His fickle nature makes him hard to trust.'},
    {"word": 'Grumble', "meaning": 'To complain in a low, discontented tone', "hindi": 'बुड़बुड़ाना, शिकायत करना', "example": 'He grumbled about the long queue.'},
    {"word": 'Haphazard', "meaning": 'Lacking order or organization; random', "hindi": 'बिना सोचे-समझे, अनियंत्रित', "example": 'The files were arranged in a haphazard way.'},
    {"word": 'Illicit', "meaning": 'Forbidden by law or rules', "hindi": 'गैर-कानूनी', "example": 'The police seized illicit goods at the border.'},
    {"word": 'Jubilant', "meaning": 'Feeling or expressing great happiness', "hindi": 'अति-प्रसन्न, खुशी से भरा', "example": 'The team was jubilant after winning the match.'},
    {"word": 'Lament', "meaning": 'To express sorrow or regret', "hindi": 'विलाप करना, दुख व्यक्त करना', "example": 'She lamented the loss of her old friend.'},
    {"word": 'Mediocre', "meaning": 'Of only average quality', "hindi": 'साधारण, औसत', "example": 'The food at that restaurant was mediocre.'},
    {"word": 'Novice', "meaning": 'A person new to a skill or activity', "hindi": 'नया-सीखने वाला, अनुभवहीन', "example": 'As a novice cook, he burned the rice twice.'},
    {"word": 'Ominous', "meaning": 'Giving the impression something bad will happen', "hindi": 'अशुभ, खतरे का संकेत देने वाला', "example": 'Dark clouds gave an ominous feeling.'},
    {"word": 'Perceive', "meaning": 'To become aware of through the senses', "hindi": 'अनुभव करना, समझना', "example": 'She perceived a change in his tone.'},
    {"word": 'Quandary', "meaning": 'A state of uncertainty or difficult choice', "hindi": 'दुविधा, उलझन', "example": "I'm in a quandary about which job to accept."},
    {"word": 'Reckless', "meaning": 'Without thinking about danger or consequences', "hindi": 'लापरवाह, बिना सोचे करने वाला', "example": 'Reckless driving causes many accidents.'},
    {"word": 'Sturdy', "meaning": 'Strongly built; solid', "hindi": 'मज़बूत', "example": 'We need a sturdy table for the workshop.'},
    {"word": 'Trivial', "meaning": 'Of little value or importance', "hindi": 'छोटा-मोटा, महत्वहीन', "example": "Don't waste time on trivial issues."},
    {"word": 'Unveil', "meaning": 'To remove a cover from; to reveal', "hindi": 'पर्दाफाश करना, दिखाना', "example": 'The company will unveil its new product tomorrow.'},
    {"word": 'Vulnerable', "meaning": 'Easily hurt physically or emotionally', "hindi": 'कमज़ोर, आसानी से चोट लगने वाला', "example": 'Children can be vulnerable to online scams.'},
    {"word": 'Wholesome', "meaning": 'Good for health or well-being', "hindi": 'स्वास्थ्यवर्धक', "example": 'Home-cooked food is wholesome and healthy.'},
    {"word": 'Abrupt', "meaning": 'Sudden and unexpected', "hindi": 'अचानक', "example": 'The meeting came to an abrupt end.'},
    {"word": 'Benign', "meaning": 'Gentle and kind; not harmful', "hindi": 'सौम्य, हानिकारक नहीं', "example": 'The doctor confirmed the tumor was benign.'},
    {"word": 'Cordial', "meaning": 'Warm and friendly', "hindi": 'सौहार्दपूर्ण, दोस्ताना', "example": 'They shared a cordial handshake.'},
    {"word": 'Dubious', "meaning": 'Hesitant or doubtful', "hindi": 'संदेहास्पद', "example": "I'm dubious about his intentions."},
    {"word": 'Exemplary', "meaning": 'Serving as a good example', "hindi": 'आदर्श, उत्तम', "example": 'Her behavior was exemplary throughout the trip.'},
]
